# Generated by Django 5.2.12 on 2026-03-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reservation',
            new_name='room_reserv_room_id_17806d_idx',
            old_name='room_reser_room_id_5ed067_idx',
        ),
    ]
