# Generated by Django 5.2.12 on 2026-03-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservations', '0005_roomguardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='attributes',
            field=models.ManyToManyField(blank=True, help_text='Lista atrybutow sali, np. komputer, rzutnik, mikroskop, tablica.', related_name='rooms', to='room_reservations.attribute'),
        ),
    ]
