# Generated by Django 5.2.12 on 2026-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_reservations", "0007_reservation_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="title",
            field=models.CharField(help_text="Tytul rezerwacji.", max_length=200),
        ),
    ]
