# Generated by Django 5.2.12 on 2026-03-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room_reservations", "0008_alter_reservation_title"),
        ("room_reservations", "0008_alter_reservation_title_required"),
    ]

    operations = []
