# Generated by Django 5.2.12 on 2026-03-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_reservations", "0009_merge_0008_title_branches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="title",
            field=models.CharField(help_text="Tytul rezerwacji.", max_length=200),
        ),
    ]
